// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-variants/Compact.tsx": () => import("../components/mockups/dashboard-variants/Compact.tsx"),
  "./components/mockups/dashboard-variants/DataFirst.tsx": () => import("../components/mockups/dashboard-variants/DataFirst.tsx"),
  "./components/mockups/dashboard-variants/SidebarFocus.tsx": () => import("../components/mockups/dashboard-variants/SidebarFocus.tsx")
};
